// GENERATED FILE — do not hand-edit.
//
// Regenerated from Dr. K's master food priority list CSV (docs/PLAN.md
// Post-demo milestone #3) via a one-off transform script — see that plan
// entry for how to re-run it if the source list changes. Merged into
// src/lib/nutrient-reference.ts's NUTRIENT_FOODS at import time; a
// hand-curated entry there always wins on a name collision (see
// mergeFoodLists), so this file only ever *adds* coverage, never
// overrides last session's voice-checked copy. Only covers the 14
// nutrients the source CSV tracks — TRACKED_NUTRIENTS grew to ~27 in a
// later, separately-merged session (docs/ETHOS.md principle 3), so this
// is deliberately a Partial, not every tracked nutrient.
import type { TrackedNutrient } from "@/lib/analysis.schema";
import type { NutrientFood } from "@/lib/nutrient-reference";

export const IMPORTED_FOODS: Partial<Record<TrackedNutrient, NutrientFood[]>> = {
  iron: [
    {
      name: "Lentils, cooked",
      reason: "soups, shepherd's pie base, everyday pantry staple",
      cuisines: ["Canadian / North American"],
      vegan: true,
      amount: 6.6,
      servingSize: "1 cup",
    },
    {
      name: "Fortified oats or cream of wheat",
      reason: "breakfast staple, iron-fortified",
      cuisines: ["Canadian / North American"],
      vegan: true,
      amount: 9.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Pumpkin seeds",
      reason: "snack, salad topper, granola mix-in",
      cuisines: ["Canadian / North American"],
      vegan: true,
      amount: 2.5,
      servingSize: "1 oz / 28g",
    },
    {
      name: "Buckwheat (hrechka), cooked",
      reason: "daily staple grain, side or porridge",
      cuisines: ["Ukrainian / Eastern European"],
      vegan: true,
      amount: 1.9,
      servingSize: "1 cup",
    },
    {
      name: "Beef liver pate",
      reason: "traditional Ukrainian/Baltic spread on rye bread",
      cuisines: ["Ukrainian / Eastern European"],
      vegan: false,
      amount: 5.5,
      servingSize: "50g",
    },
    {
      name: "Beet borscht with beans",
      reason: "classic Ukrainian soup, beets + beans combo",
      cuisines: ["Ukrainian / Eastern European"],
      vegan: true,
      amount: 3.5,
      servingSize: "1 bowl",
    },
    {
      name: "White beans (cannellini)",
      reason: "ribollita, pasta e fagioli",
      cuisines: ["Italian"],
      vegan: true,
      amount: 4.5,
      servingSize: "1 cup cooked",
    },
    {
      name: "Farro, cooked",
      reason: "traditional grain salad base",
      cuisines: ["Italian"],
      vegan: true,
      amount: 2.6,
      servingSize: "1 cup",
    },
    {
      name: "Cuttlefish/squid (seppia)",
      reason: "coastal Italian seafood staple, pairs with iron-C foods",
      cuisines: ["Italian"],
      vegan: false,
      amount: 1.2,
      servingSize: "100g",
    },
    {
      name: "Chickpeas (garbanzos)",
      reason: "cocido, potaje de garbanzos",
      cuisines: ["Spanish / Mediterranean"],
      vegan: true,
      amount: 4.7,
      servingSize: "1 cup cooked",
    },
    {
      name: "Clams (almejas)",
      reason: "common in Spanish coastal cooking",
      cuisines: ["Spanish / Mediterranean"],
      vegan: false,
      amount: 3.0,
      servingSize: "100g",
    },
    {
      name: "Spinach (espinacas a la catalana)",
      reason: "classic Spanish preparation with pine nuts/raisins",
      cuisines: ["Spanish / Mediterranean"],
      vegan: true,
      amount: 3.6,
      servingSize: "1 cup cooked",
    },
    {
      name: "Black beans, cooked",
      reason: "daily staple, frijoles",
      cuisines: ["Mexican"],
      vegan: true,
      amount: 3.6,
      servingSize: "1 cup",
    },
    {
      name: "Pepitas (pumpkin seeds)",
      reason: "mole base, snacking",
      cuisines: ["Mexican"],
      vegan: true,
      amount: 2.5,
      servingSize: "1 oz",
    },
    {
      name: "Nopales (cactus paddle)",
      reason: "traditional vegetable, pair with lime for absorption",
      cuisines: ["Mexican"],
      vegan: true,
      amount: 1.2,
      servingSize: "1 cup cooked",
    },
    {
      name: "Black beans (frijoles negros)",
      reason: "moros y cristianos, daily staple",
      cuisines: ["Cuban / Caribbean"],
      vegan: true,
      amount: 3.6,
      servingSize: "1 cup cooked",
    },
    {
      name: "Callaloo (leafy green)",
      reason: "caribbean leafy green stew base",
      cuisines: ["Cuban / Caribbean"],
      vegan: true,
      amount: 1.8,
      servingSize: "1 cup cooked",
    },
    {
      name: "Pigeon peas (gandules)",
      reason: "rice and peas staple",
      cuisines: ["Cuban / Caribbean"],
      vegan: true,
      amount: 2.2,
      servingSize: "1 cup cooked",
    },
    {
      name: "Black-eyed peas",
      reason: "stews, akara fritters",
      cuisines: ["West African"],
      vegan: true,
      amount: 4.3,
      servingSize: "1 cup cooked",
    },
    {
      name: "Egusi (melon seed) stew base",
      reason: "staple soup base across West Africa",
      cuisines: ["West African"],
      vegan: true,
      amount: 3.5,
      servingSize: "1/2 cup seeds",
    },
    {
      name: "Millet, cooked",
      reason: "porridge, tuwo",
      cuisines: ["West African"],
      vegan: true,
      amount: 2.0,
      servingSize: "1 cup",
    },
    {
      name: "Teff, cooked (injera base)",
      reason: "ethiopian/Eritrean daily staple grain",
      cuisines: ["East African"],
      vegan: true,
      amount: 5.0,
      servingSize: "1 cup",
    },
    {
      name: "Lentils (misir wot)",
      reason: "classic Ethiopian stew",
      cuisines: ["East African"],
      vegan: true,
      amount: 6.6,
      servingSize: "1 cup cooked",
    },
    {
      name: "Amaranth greens",
      reason: "common East African leafy green",
      cuisines: ["East African"],
      vegan: true,
      amount: 2.3,
      servingSize: "1 cup cooked",
    },
    {
      name: "Masoor dal (red lentils), cooked",
      reason: "daily staple dal",
      cuisines: ["South Asian (Indian)"],
      vegan: true,
      amount: 6.6,
      servingSize: "1 cup",
    },
    {
      name: "Chana (chickpeas)",
      reason: "chana masala, chole",
      cuisines: ["South Asian (Indian)"],
      vegan: true,
      amount: 4.7,
      servingSize: "1 cup cooked",
    },
    {
      name: "Ragi (finger millet)",
      reason: "south Indian porridge, roti",
      cuisines: ["South Asian (Indian)"],
      vegan: true,
      amount: 2.5,
      servingSize: "1 cup cooked",
    },
    {
      name: "Tofu, firm",
      reason: "common protein base across the region",
      cuisines: ["Southeast Asian"],
      vegan: true,
      amount: 3.4,
      servingSize: "1/2 cup",
    },
    {
      name: "Water spinach (kangkong/rau muong)",
      reason: "stir-fried staple green",
      cuisines: ["Southeast Asian"],
      vegan: true,
      amount: 2.5,
      servingSize: "1 cup cooked",
    },
    {
      name: "Mung beans",
      reason: "sweet and savoury dishes, sprouts",
      cuisines: ["Southeast Asian"],
      vegan: true,
      amount: 2.8,
      servingSize: "1 cup cooked",
    },
    {
      name: "Edamame",
      reason: "snack, side dish",
      cuisines: ["East Asian"],
      vegan: true,
      amount: 3.5,
      servingSize: "1 cup",
    },
    {
      name: "Dried shiitake mushrooms",
      reason: "umami base for broths and stir-fries",
      cuisines: ["East Asian"],
      vegan: true,
      amount: 1.0,
      servingSize: "4 mushrooms",
    },
    {
      name: "Spinach (ohitashi)",
      reason: "japanese blanched spinach side",
      cuisines: ["East Asian"],
      vegan: true,
      amount: 3.6,
      servingSize: "1 cup cooked",
    },
    {
      name: "Lentils (mujadara)",
      reason: "lentils and rice staple",
      cuisines: ["Middle Eastern"],
      vegan: true,
      amount: 6.6,
      servingSize: "1 cup cooked",
    },
    {
      name: "Hummus (chickpea base)",
      reason: "daily staple spread",
      cuisines: ["Middle Eastern"],
      vegan: true,
      amount: 2.4,
      servingSize: "1/2 cup",
    },
    {
      name: "Dried apricots",
      reason: "common snack, pair with lemon/citrus",
      cuisines: ["Middle Eastern"],
      vegan: true,
      amount: 0.8,
      servingSize: "1/4 cup",
    },
    {
      name: "Kidney beans, cooked",
      reason: "universally available, budget-friendly",
      vegan: true,
      amount: 5.2,
      servingSize: "1 cup",
    },
    {
      name: "Dark chocolate (70%+)",
      reason: "widely available treat option",
      vegan: true,
      amount: 3.3,
      servingSize: "1 oz",
    },
    {
      name: "Spinach",
      reason: "available in most grocery stores globally",
      vegan: true,
      amount: 3.6,
      servingSize: "1 cup cooked",
    },
    {
      name: "Soybeans / edamame, cooked",
      reason: "highest plant iron source in the guide; also protein 29g, calcium 175mg",
      cuisines: ["East Asian"],
      vegan: true,
      amount: 8.8,
      servingSize: "1 cup",
    },
    {
      name: "Chickpeas, cooked",
      reason: "also B6 1.1mg, magnesium 79mg",
      cuisines: ["Middle Eastern", "South Asian (Indian)", "Spanish / Mediterranean"],
      vegan: true,
      amount: 4.7,
      servingSize: "1 cup",
    },
    {
      name: "Blackstrap molasses",
      reason: "also calcium 200mg, magnesium 48mg",
      cuisines: ["Cuban / Caribbean", "Canadian / North American"],
      vegan: true,
      amount: 3.5,
      servingSize: "1 tbsp",
    },
    {
      name: "Spinach, cooked",
      reason: "also magnesium 78mg, folate 131mcg",
      vegan: true,
      amount: 3.2,
      servingSize: "1/2 cup",
    },
    {
      name: "Tahini (sesame paste)",
      reason: "also calcium 128mg, zinc 1.4mg",
      cuisines: ["Middle Eastern", "Spanish / Mediterranean"],
      vegan: true,
      amount: 2.6,
      servingSize: "2 tbsp",
    },
  ],
  b12: [
    {
      name: "Fortified nutritional yeast",
      reason: "cheesy flavour, common vegan staple",
      cuisines: ["Canadian / North American"],
      vegan: true,
      amount: 16.0,
      servingSize: "2 tbsp",
    },
    {
      name: "Eggs",
      reason: "breakfast staple",
      cuisines: ["Canadian / North American"],
      vegan: false,
      amount: 1.2,
      servingSize: "2 whole",
    },
    {
      name: "Fortified plant milk",
      reason: "check label for fortification level",
      cuisines: ["Canadian / North American"],
      vegan: true,
      amount: 2.0,
      servingSize: "1 cup",
    },
    {
      name: "Herring",
      reason: "traditional preserved fish",
      cuisines: ["Ukrainian / Eastern European"],
      vegan: false,
      amount: 13.0,
      servingSize: "100g",
    },
    {
      name: "Beef liver",
      reason: "traditional organ meat use",
      cuisines: ["Ukrainian / Eastern European"],
      vegan: false,
      amount: 35.0,
      servingSize: "50g",
    },
    {
      name: "Kefir",
      reason: "daily fermented dairy staple",
      cuisines: ["Ukrainian / Eastern European"],
      vegan: false,
      amount: 1.0,
      servingSize: "1 cup",
    },
    {
      name: "Clams (vongole)",
      reason: "pasta alle vongole",
      cuisines: ["Italian"],
      vegan: false,
      amount: 98.0,
      servingSize: "100g",
    },
    {
      name: "Parmesan cheese",
      reason: "modest but frequent contributor",
      cuisines: ["Italian"],
      vegan: false,
      amount: 0.3,
      servingSize: "1 oz",
    },
    {
      name: "Anchovies",
      reason: "common flavour base",
      cuisines: ["Italian"],
      vegan: false,
      amount: 0.5,
      servingSize: "5 fillets",
    },
    {
      name: "Clams/mussels",
      reason: "common tapas item",
      cuisines: ["Spanish / Mediterranean"],
      vegan: false,
      amount: 59.0,
      servingSize: "100g",
    },
    {
      name: "Octopus (pulpo)",
      reason: "traditional Galician dish",
      cuisines: ["Spanish / Mediterranean"],
      vegan: false,
      amount: 20.0,
      servingSize: "100g",
    },
    {
      name: "Manchego cheese",
      reason: "modest contributor",
      cuisines: ["Spanish / Mediterranean"],
      vegan: false,
      amount: 0.3,
      servingSize: "1 oz",
    },
    {
      name: "Beef/tripe (menudo)",
      reason: "traditional soup",
      cuisines: ["Mexican"],
      vegan: false,
      amount: 2.5,
      servingSize: "100g",
    },
    {
      name: "Queso fresco",
      reason: "common topping",
      cuisines: ["Mexican"],
      vegan: false,
      amount: 0.3,
      servingSize: "1 oz",
    },
    {
      name: "Canned tuna",
      reason: "affordable staple",
      cuisines: ["Mexican"],
      vegan: false,
      amount: 2.5,
      servingSize: "100g",
    },
    {
      name: "Canned sardines",
      reason: "budget-friendly staple",
      cuisines: ["Cuban / Caribbean"],
      vegan: false,
      amount: 8.9,
      servingSize: "100g",
    },
    {
      name: "Egg",
      reason: "common breakfast item",
      cuisines: ["Cuban / Caribbean"],
      vegan: false,
      amount: 0.6,
      servingSize: "1 whole",
    },
    {
      name: "Queso blanco",
      reason: "modest contributor",
      cuisines: ["Cuban / Caribbean"],
      vegan: false,
      amount: 0.3,
      servingSize: "1 oz",
    },
    {
      name: "Dried/smoked fish",
      reason: "common soup addition",
      cuisines: ["West African"],
      vegan: false,
      amount: 4.0,
      servingSize: "50g",
    },
    {
      name: "Goat meat",
      reason: "traditional stew protein",
      cuisines: ["West African"],
      vegan: false,
      amount: 1.0,
      servingSize: "100g",
    },
    {
      name: "Nile perch/tilapia",
      reason: "regional fish staple",
      cuisines: ["East African"],
      vegan: false,
      amount: 2.0,
      servingSize: "100g",
    },
    {
      name: "Yogurt (ergo)",
      reason: "traditional fermented dairy",
      cuisines: ["East African"],
      vegan: false,
      amount: 1.0,
      servingSize: "1 cup",
    },
    {
      name: "Yogurt/lassi",
      reason: "daily staple, especially in vegetarian households",
      cuisines: ["South Asian (Indian)"],
      vegan: false,
      amount: 1.0,
      servingSize: "1 cup",
    },
    {
      name: "Paneer",
      reason: "common protein for vegetarians",
      cuisines: ["South Asian (Indian)"],
      vegan: false,
      amount: 0.5,
      servingSize: "1/2 cup",
    },
    {
      name: "Fish (rohu, hilsa)",
      reason: "where non-vegetarian",
      cuisines: ["South Asian (Indian)"],
      vegan: false,
      amount: 2.5,
      servingSize: "100g",
    },
    {
      name: "Fish sauce-based dishes / small fish",
      reason: "common across the region",
      cuisines: ["Southeast Asian"],
      vegan: false,
      amount: 1.5,
      servingSize: "1 serving",
    },
    {
      name: "Shrimp",
      reason: "common protein",
      cuisines: ["Southeast Asian"],
      vegan: false,
      amount: 1.4,
      servingSize: "100g",
    },
    {
      name: "Nori seaweed",
      reason:
        "contains B12 analogues; not a reliable sole source - flag for supplementation if plant-forward",
      cuisines: ["East Asian"],
      vegan: true,
      servingSize: "1 sheet",
    },
    {
      name: "Fish (mackerel, salmon)",
      reason: "common regional protein",
      cuisines: ["East Asian"],
      vegan: false,
      amount: 7.5,
      servingSize: "100g",
    },
    {
      name: "Labneh/yogurt",
      reason: "daily staple",
      cuisines: ["Middle Eastern"],
      vegan: false,
      amount: 0.75,
      servingSize: "1/2 cup",
    },
    {
      name: "Lamb",
      reason: "traditional protein source",
      cuisines: ["Middle Eastern"],
      vegan: false,
      amount: 2.6,
      servingSize: "100g",
    },
    {
      name: "Kimchi, sauerkraut, kombucha, miso, tempeh (fermented foods)",
      reason:
        "contribute to overall B status but do not reliably maintain B12 on a fully plant-based diet — supplementation still needed",
      cuisines: ["Ukrainian / Eastern European"],
      vegan: true,
      servingSize: "daily serving",
    },
  ],
  vitamin_d: [
    {
      name: "Fortified plant milk",
      reason: "standard Canadian fortification",
      cuisines: ["Canadian / North American"],
      vegan: true,
      amount: 2.5,
      servingSize: "1 cup",
    },
    {
      name: "Canned sockeye salmon",
      reason: "pantry staple, wild-caught preferred",
      cuisines: ["Canadian / North American"],
      vegan: false,
      amount: 13.75,
      servingSize: "100g",
    },
    {
      name: "Egg yolk",
      reason: "breakfast staple",
      cuisines: ["Canadian / North American"],
      vegan: false,
      amount: 2.0,
      servingSize: "2 yolks",
    },
    {
      name: "Herring (oseledets)",
      reason: "traditional preserved fish",
      cuisines: ["Ukrainian / Eastern European"],
      vegan: false,
      amount: 6.25,
      servingSize: "100g",
    },
    {
      name: "Mushrooms, UV-exposed/sun-dried",
      reason: "foraged mushroom tradition",
      cuisines: ["Ukrainian / Eastern European"],
      vegan: true,
      amount: 6.88,
      servingSize: "1 cup",
    },
    {
      name: "Sardines",
      reason: "common pantry fish",
      cuisines: ["Italian"],
      vegan: false,
      amount: 7.5,
      servingSize: "100g",
    },
    {
      name: "Porcini mushrooms, dried, sun-exposed",
      reason: "common in risotto",
      cuisines: ["Italian"],
      vegan: true,
      amount: 3.75,
      servingSize: "1/2 cup",
    },
    {
      name: "Sardines/anchovies (boquerones)",
      reason: "tapas staple",
      cuisines: ["Spanish / Mediterranean"],
      vegan: false,
      amount: 8.75,
      servingSize: "100g",
    },
    {
      name: "Mackerel",
      reason: "grilled or canned",
      cuisines: ["Spanish / Mediterranean"],
      vegan: false,
      amount: 8.75,
      servingSize: "100g",
    },
    {
      name: "Canned tuna or sardines",
      reason: "affordable pantry staple",
      cuisines: ["Mexican"],
      vegan: false,
      amount: 6.25,
      servingSize: "100g",
    },
    {
      name: "Egg",
      reason: "huevos rancheros, daily staple",
      cuisines: ["Mexican"],
      vegan: false,
      amount: 1.0,
      servingSize: "1 whole",
    },
    {
      name: "Fortified milk",
      reason: "where available",
      cuisines: ["Mexican"],
      vegan: false,
      amount: 2.5,
      servingSize: "1 cup",
    },
    {
      name: "Canned sardines/mackerel",
      reason: "budget-friendly staple",
      cuisines: ["Cuban / Caribbean"],
      vegan: false,
      amount: 7.5,
      servingSize: "100g",
    },
    {
      name: "Sun-dried fish",
      reason: "traditional preservation method",
      cuisines: ["Cuban / Caribbean"],
      vegan: false,
      amount: 3.75,
      servingSize: "50g",
    },
    {
      name: "Dried/smoked fish",
      reason: "common soup addition",
      cuisines: ["West African"],
      vegan: false,
      amount: 5.0,
      servingSize: "50g",
    },
    {
      name: "Palm oil (red)",
      reason: "supports fat-soluble vitamin absorption when paired with D sources",
      cuisines: ["West African"],
      vegan: true,
      servingSize: "1 tbsp",
    },
    {
      name: "Sardines/small dried fish (omena)",
      reason: "lake Victoria region staple",
      cuisines: ["East African"],
      vegan: false,
      amount: 3.75,
      servingSize: "50g",
    },
    {
      name: "Sun exposure emphasis",
      reason: "east African latitude allows strong skin synthesis most of year",
      cuisines: ["East African"],
      vegan: false,
      servingSize: "n/a",
    },
    {
      name: "Fatty fish (rohu, hilsa)",
      reason: "bengali/coastal staple",
      cuisines: ["South Asian (Indian)"],
      vegan: false,
      amount: 7.5,
      servingSize: "100g",
    },
    {
      name: "Mackerel/sardines",
      reason: "common fish staple",
      cuisines: ["Southeast Asian"],
      vegan: false,
      amount: 8.75,
      servingSize: "100g",
    },
    {
      name: "Dried shrimp",
      reason: "common flavour base",
      cuisines: ["Southeast Asian"],
      vegan: false,
      amount: 1.25,
      servingSize: "1 oz",
    },
    {
      name: "Salmon",
      reason: "common in Japanese/Korean cuisine",
      cuisines: ["East Asian"],
      vegan: false,
      amount: 13.75,
      servingSize: "100g",
    },
    {
      name: "Dried shiitake, sun-exposed",
      reason: "traditional sun-drying boosts vitamin D",
      cuisines: ["East Asian"],
      vegan: true,
      amount: 6.88,
      servingSize: "4 mushrooms",
    },
    {
      name: "Sardines/mackerel",
      reason: "common fish option",
      cuisines: ["Middle Eastern"],
      vegan: false,
      amount: 7.5,
      servingSize: "100g",
    },
    {
      name: "Fortified labneh/yogurt",
      reason: "where fortified products available",
      cuisines: ["Middle Eastern"],
      vegan: false,
      amount: 1.88,
      servingSize: "1/2 cup",
    },
    {
      name: "Fatty fish (salmon, sardines, mackerel)",
      reason: "widely available",
      vegan: false,
      amount: 11.25,
      servingSize: "100g",
    },
    {
      name: "Maitake mushrooms, raw, UV-exposed",
      reason: "best whole-food vegan source in the guide",
      cuisines: ["East Asian"],
      vegan: true,
      servingSize: "1/2 cup",
    },
    {
      name: "Portobello mushrooms, UV-exposed",
      reason: "gills-up in direct sun 30 min",
      cuisines: ["Canadian / North American", "Italian"],
      vegan: true,
      amount: 17.5,
      servingSize: "1/2 cup",
    },
    {
      name: "Shiitake mushrooms, sun-dried",
      reason: "traditional drying method",
      cuisines: ["East Asian"],
      vegan: true,
      servingSize: "4 pieces",
    },
    {
      name: "White button mushrooms, UV-labeled",
      reason: "look for a UV-treated label at the store",
      cuisines: ["Canadian / North American"],
      vegan: true,
      servingSize: "1/2 cup",
    },
    {
      name: "Morel mushrooms",
      reason: "wild foraged",
      cuisines: ["Canadian / North American"],
      vegan: true,
      servingSize: "1/2 cup",
    },
  ],
  calcium: [
    {
      name: "Fortified plant milk (soy/oat)",
      reason: "common dairy alternative, check label",
      cuisines: ["Canadian / North American"],
      vegan: true,
      amount: 375.0,
      servingSize: "1 cup",
    },
    {
      name: "Cheddar cheese",
      reason: "standard grocery staple",
      cuisines: ["Canadian / North American"],
      vegan: false,
      amount: 300.0,
      servingSize: "1.5 oz",
    },
    {
      name: "Canned salmon with bones",
      reason: "budget-friendly, pantry staple",
      cuisines: ["Canadian / North American"],
      vegan: false,
      amount: 200.0,
      servingSize: "100g",
    },
    {
      name: "Kefir",
      reason: "traditional fermented dairy staple",
      cuisines: ["Ukrainian / Eastern European"],
      vegan: false,
      amount: 300.0,
      servingSize: "1 cup",
    },
    {
      name: "Farmer's cheese (tvorog)",
      reason: "used in syrniki, varenyky filling",
      cuisines: ["Ukrainian / Eastern European"],
      vegan: false,
      amount: 130.0,
      servingSize: "1/2 cup",
    },
    {
      name: "Poppy seeds",
      reason: "traditional in baking (makivnyk)",
      cuisines: ["Ukrainian / Eastern European"],
      vegan: true,
      amount: 260.0,
      servingSize: "2 tbsp",
    },
    {
      name: "Parmesan cheese",
      reason: "grated into nearly every dish",
      cuisines: ["Italian"],
      vegan: false,
      amount: 330.0,
      servingSize: "1 oz",
    },
    {
      name: "White beans",
      reason: "ribollita, minestrone",
      cuisines: ["Italian"],
      vegan: true,
      amount: 160.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Sardines with bones",
      reason: "common Italian pantry fish",
      cuisines: ["Italian"],
      vegan: false,
      amount: 380.0,
      servingSize: "100g",
    },
    {
      name: "Manchego cheese",
      reason: "traditional Spanish sheep's cheese",
      cuisines: ["Spanish / Mediterranean"],
      vegan: false,
      amount: 200.0,
      servingSize: "1 oz",
    },
    {
      name: "Sardines (sardinas)",
      reason: "coastal staple, canned or grilled",
      cuisines: ["Spanish / Mediterranean"],
      vegan: false,
      amount: 380.0,
      servingSize: "100g",
    },
    {
      name: "Almonds",
      reason: "snacking, turron, marcona almonds",
      cuisines: ["Spanish / Mediterranean"],
      vegan: true,
      amount: 75.0,
      servingSize: "1 oz",
    },
    {
      name: "Corn tortillas (nixtamalized)",
      reason: "lime-processing increases calcium availability",
      cuisines: ["Mexican"],
      vegan: true,
      amount: 90.0,
      servingSize: "2 tortillas",
    },
    {
      name: "Queso fresco",
      reason: "common topping",
      cuisines: ["Mexican"],
      vegan: false,
      amount: 125.0,
      servingSize: "1 oz",
    },
    {
      name: "Chia seeds",
      reason: "chia fresca drink, pudding",
      cuisines: ["Mexican"],
      vegan: true,
      amount: 180.0,
      servingSize: "2 tbsp",
    },
    {
      name: "Queso blanco",
      reason: "common in Cuban breakfast",
      cuisines: ["Cuban / Caribbean"],
      vegan: false,
      amount: 150.0,
      servingSize: "1 oz",
    },
    {
      name: "Okra",
      reason: "caribbean stews",
      cuisines: ["Cuban / Caribbean"],
      vegan: true,
      amount: 100.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Canned sardines",
      reason: "affordable, widely available",
      cuisines: ["Cuban / Caribbean"],
      vegan: false,
      amount: 380.0,
      servingSize: "100g",
    },
    {
      name: "Egusi seeds",
      reason: "soup base",
      cuisines: ["West African"],
      vegan: true,
      amount: 60.0,
      servingSize: "1/2 cup",
    },
    {
      name: "Moringa leaves, dried powder",
      reason: "traditional nutrient-dense green",
      cuisines: ["West African"],
      vegan: true,
      amount: 125.0,
      servingSize: "1 tbsp",
    },
    {
      name: "Smoked/dried fish with bones",
      reason: "common soup and stew addition",
      cuisines: ["West African"],
      vegan: false,
      amount: 200.0,
      servingSize: "50g",
    },
    {
      name: "Teff",
      reason: "injera base, notably calcium-rich grain",
      cuisines: ["East African"],
      vegan: true,
      amount: 125.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Collard greens (gomen)",
      reason: "traditional Ethiopian side",
      cuisines: ["East African"],
      vegan: true,
      amount: 270.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Yogurt (ergo)",
      reason: "traditional fermented dairy",
      cuisines: ["East African"],
      vegan: false,
      amount: 300.0,
      servingSize: "1 cup",
    },
    {
      name: "Paneer",
      reason: "daily staple protein",
      cuisines: ["South Asian (Indian)"],
      vegan: false,
      amount: 300.0,
      servingSize: "1/2 cup",
    },
    {
      name: "Ragi (finger millet)",
      reason: "notably one of the highest calcium grains",
      cuisines: ["South Asian (Indian)"],
      vegan: true,
      amount: 340.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Sesame seeds (til)",
      reason: "chutneys, laddoo, garnish",
      cuisines: ["South Asian (Indian)"],
      vegan: true,
      amount: 175.0,
      servingSize: "2 tbsp",
    },
    {
      name: "Tofu, calcium-set",
      reason: "common protein base",
      cuisines: ["Southeast Asian"],
      vegan: true,
      amount: 250.0,
      servingSize: "1/2 cup",
    },
    {
      name: "Bok choy",
      reason: "common stir-fry green",
      cuisines: ["Southeast Asian"],
      vegan: true,
      amount: 160.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Small dried shrimp/anchovies (whole, with shell)",
      reason: "common flavour base across the region",
      cuisines: ["Southeast Asian"],
      vegan: false,
      amount: 300.0,
      servingSize: "1 oz",
    },
    {
      name: "Sesame seeds/tahini",
      reason: "banchan, dressings",
      cuisines: ["East Asian"],
      vegan: true,
      amount: 175.0,
      servingSize: "2 tbsp",
    },
    {
      name: "Tahini (sesame paste)",
      reason: "hummus, baba ganoush base",
      cuisines: ["Middle Eastern"],
      vegan: true,
      amount: 130.0,
      servingSize: "2 tbsp",
    },
    {
      name: "Yogurt (labneh)",
      reason: "daily staple",
      cuisines: ["Middle Eastern"],
      vegan: false,
      amount: 150.0,
      servingSize: "1/2 cup",
    },
    {
      name: "Dried figs",
      reason: "common snack",
      cuisines: ["Middle Eastern"],
      vegan: true,
      amount: 60.0,
      servingSize: "1/4 cup",
    },
    {
      name: "Fortified plant or dairy milk",
      reason: "widely available worldwide",
      vegan: false,
      amount: 300.0,
      servingSize: "1 cup",
    },
    {
      name: "Canned fish with bones",
      reason: "widely available, budget-friendly",
      vegan: false,
      amount: 290.0,
      servingSize: "100g",
    },
    {
      name: "Sesame seeds, whole",
      reason: "also zinc, iron 2.4mg",
      cuisines: ["Middle Eastern", "East Asian", "South Asian (Indian)"],
      vegan: true,
      amount: 280.0,
      servingSize: "1 oz",
    },
    {
      name: "Collard greens, cooked",
      reason: "low oxalate, high bioavailability (~53%)",
      cuisines: ["West African", "Canadian / North American"],
      vegan: true,
      amount: 268.0,
      servingSize: "1 cup",
    },
    {
      name: "Blackstrap molasses",
      reason: "also iron 3.5mg",
      cuisines: ["Cuban / Caribbean", "Canadian / North American"],
      vegan: true,
      amount: 200.0,
      servingSize: "1 tbsp",
    },
    {
      name: "Bok choy, cooked",
      reason: "excellent bioavailability (~54%)",
      cuisines: ["East Asian", "Southeast Asian"],
      vegan: true,
      amount: 158.0,
      servingSize: "1 cup",
    },
    {
      name: "White / navy beans, cooked",
      reason: "also protein, iron",
      vegan: true,
      amount: 126.0,
      servingSize: "1 cup",
    },
    {
      name: "Kale, cooked",
      reason:
        "good bioavailability (~40%); spinach is not on this list due to oxalate limiting absorption to ~5%",
      vegan: true,
      amount: 94.0,
      servingSize: "1 cup",
    },
  ],
  omega_3: [
    {
      name: "Ground flaxseed",
      reason: "everyday pantry staple, add to oatmeal/smoothies",
      cuisines: ["Canadian / North American"],
      vegan: true,
      amount: 3.2,
      servingSize: "2 tbsp",
    },
    {
      name: "Canned salmon",
      reason: "budget-friendly, wild-caught preferred",
      cuisines: ["Canadian / North American"],
      vegan: false,
      amount: 1.75,
      servingSize: "100g",
    },
    {
      name: "Walnuts",
      reason: "snacking, baking",
      cuisines: ["Canadian / North American"],
      vegan: true,
      amount: 2.5,
      servingSize: "1 oz",
    },
    {
      name: "Flaxseed / flax oil",
      reason: "traditional Slavic staple, salad dressing",
      cuisines: ["Ukrainian / Eastern European"],
      vegan: true,
      amount: 7.3,
      servingSize: "1 tbsp oil",
    },
    {
      name: "Herring",
      reason: "traditional preserved fish",
      cuisines: ["Ukrainian / Eastern European"],
      vegan: false,
      amount: 1.7,
      servingSize: "100g",
    },
    {
      name: "Sardines/anchovies",
      reason: "common pantry fish",
      cuisines: ["Italian"],
      vegan: false,
      amount: 1.5,
      servingSize: "100g",
    },
    {
      name: "Olive oil",
      reason:
        "mainly monounsaturated; not a primary omega-3 source but supports overall lipid profile",
      cuisines: ["Italian"],
      vegan: true,
      servingSize: "n/a",
    },
    {
      name: "Sardines/mackerel",
      reason: "coastal staple, canned or fresh",
      cuisines: ["Spanish / Mediterranean"],
      vegan: false,
      amount: 1.75,
      servingSize: "100g",
    },
    {
      name: "Flaxseed",
      reason: "less traditional but increasingly used",
      cuisines: ["Spanish / Mediterranean"],
      vegan: true,
      amount: 3.2,
      servingSize: "2 tbsp",
    },
    {
      name: "Chia seeds",
      reason: "chia fresca, traditional Mesoamerican food",
      cuisines: ["Mexican"],
      vegan: true,
      amount: 5.0,
      servingSize: "2 tbsp",
    },
    {
      name: "Sardines/canned fish",
      reason: "affordable staple",
      cuisines: ["Mexican"],
      vegan: false,
      amount: 1.5,
      servingSize: "100g",
    },
    {
      name: "Chia or flax (where available)",
      reason: "increasingly available",
      cuisines: ["Cuban / Caribbean"],
      vegan: true,
      amount: 4.0,
      servingSize: "2 tbsp",
    },
    {
      name: "Pumpkin seeds",
      reason: "common snack, modest contributor",
      cuisines: ["Cuban / Caribbean"],
      vegan: true,
      amount: 0.1,
      servingSize: "1 oz",
    },
    {
      name: "Egusi (melon seeds)",
      reason: "staple soup base, modest source",
      cuisines: ["West African"],
      vegan: true,
      amount: 0.3,
      servingSize: "1/2 cup",
    },
    {
      name: "Dried/smoked fish",
      reason: "common soup addition",
      cuisines: ["West African"],
      vegan: false,
      amount: 0.75,
      servingSize: "50g",
    },
    {
      name: "Groundnut (modest ALA)",
      reason: "primarily other fats; pair with fish sources",
      cuisines: ["West African"],
      vegan: true,
      servingSize: "n/a",
    },
    {
      name: "Nile perch/tilapia",
      reason: "regional fish staple",
      cuisines: ["East African"],
      vegan: false,
      amount: 0.75,
      servingSize: "100g",
    },
    {
      name: "Flaxseed (increasingly available)",
      reason: "growing availability in urban markets",
      cuisines: ["East African"],
      vegan: true,
      amount: 3.2,
      servingSize: "2 tbsp",
    },
    {
      name: "Chia (increasingly available)",
      reason: "growing availability",
      cuisines: ["East African"],
      vegan: true,
      amount: 5.0,
      servingSize: "2 tbsp",
    },
    {
      name: "Flaxseed (alsi)",
      reason: "traditional in some regional diets, chutneys",
      cuisines: ["South Asian (Indian)"],
      vegan: true,
      amount: 3.2,
      servingSize: "2 tbsp",
    },
    {
      name: "Fatty fish (hilsa, rohu)",
      reason: "bengali/coastal staple",
      cuisines: ["South Asian (Indian)"],
      vegan: false,
      amount: 1.5,
      servingSize: "100g",
    },
    {
      name: "Walnuts (akhrot)",
      reason: "common snack",
      cuisines: ["South Asian (Indian)"],
      vegan: true,
      amount: 2.5,
      servingSize: "1 oz",
    },
    {
      name: "Mackerel/sardines",
      reason: "common regional fish",
      cuisines: ["Southeast Asian"],
      vegan: false,
      amount: 1.75,
      servingSize: "100g",
    },
    {
      name: "Salmon/mackerel/sardines",
      reason: "daily staple across the region",
      cuisines: ["East Asian"],
      vegan: false,
      amount: 2.0,
      servingSize: "100g",
    },
    {
      name: "Perilla seed oil (deulkkae)",
      reason: "traditional Korean oil, very high ALA",
      cuisines: ["East Asian"],
      vegan: true,
      amount: 8.0,
      servingSize: "1 tbsp",
    },
    {
      name: "Canned sardines/mackerel",
      reason: "budget-friendly and widely available",
      vegan: false,
      amount: 1.75,
      servingSize: "100g",
    },
    {
      name: "Flaxseed, ground",
      reason: "best single ALA source per tablespoon in the guide",
      vegan: true,
      amount: 0.006,
      servingSize: "1 tbsp",
    },
    {
      name: "Hemp seeds",
      reason: "also complete protein, magnesium",
      cuisines: ["Canadian / North American", "Ukrainian / Eastern European"],
      vegan: true,
      amount: 0.002,
      servingSize: "3 tbsp",
    },
    {
      name: "Canola oil",
      reason: "whole-food derived cooking staple",
      cuisines: ["Canadian / North American"],
      vegan: true,
      amount: 0.001,
      servingSize: "1 tbsp",
    },
    {
      name: "Soybeans / edamame, cooked",
      reason: "also protein, iron, calcium",
      cuisines: ["East Asian"],
      vegan: true,
      amount: 0.001,
      servingSize: "1 cup",
    },
    {
      name: "Spinach, cooked",
      reason: "also iron, magnesium, folate",
      vegan: true,
      amount: 0.166,
      servingSize: "1 cup",
    },
    {
      name: "Brussels sprouts, cooked",
      reason: "also vitamin C, calcium",
      cuisines: ["Ukrainian / Eastern European", "Canadian / North American"],
      vegan: true,
      amount: 0.135,
      servingSize: "1 cup",
    },
    {
      name: "Tofu, firm",
      reason: "also protein, calcium, iron",
      cuisines: ["East Asian"],
      vegan: true,
      amount: 0.3,
      servingSize: "1/2 cup",
    },
  ],
  iodine: [
    {
      name: "Iodized table salt",
      reason: "standard Canadian fortification",
      cuisines: ["Canadian / North American"],
      vegan: true,
      amount: 71.0,
      servingSize: "1/4 tsp",
    },
    {
      name: "Cod",
      reason: "common fish option",
      cuisines: ["Canadian / North American"],
      vegan: false,
      amount: 125.0,
      servingSize: "100g",
    },
    {
      name: "Fortified plant milk",
      reason: "check label",
      cuisines: ["Canadian / North American"],
      vegan: true,
      amount: 75.0,
      servingSize: "1 cup",
    },
    {
      name: "Iodized salt",
      reason: "standard fortification",
      cuisines: ["Ukrainian / Eastern European"],
      vegan: true,
      amount: 71.0,
      servingSize: "1/4 tsp",
    },
    {
      name: "Herring",
      reason: "traditional preserved fish",
      cuisines: ["Ukrainian / Eastern European"],
      vegan: false,
      amount: 50.0,
      servingSize: "100g",
    },
    {
      name: "Kefir/dairy",
      reason: "daily staple",
      cuisines: ["Ukrainian / Eastern European"],
      vegan: false,
      amount: 60.0,
      servingSize: "1 cup",
    },
    {
      name: "Cod/anchovies",
      reason: "common pantry fish",
      cuisines: ["Italian"],
      vegan: false,
      amount: 125.0,
      servingSize: "100g",
    },
    {
      name: "Iodized salt (where used)",
      reason: "less traditional than sea salt - flag for patients",
      cuisines: ["Italian"],
      vegan: true,
      amount: 71.0,
      servingSize: "1/4 tsp",
    },
    {
      name: "Mussels/clams",
      reason: "coastal staple",
      cuisines: ["Italian"],
      vegan: false,
      amount: 125.0,
      servingSize: "100g",
    },
    {
      name: "Cod (bacalao)",
      reason: "national staple dish",
      cuisines: ["Spanish / Mediterranean"],
      vegan: false,
      amount: 125.0,
      servingSize: "100g",
    },
    {
      name: "Shrimp",
      reason: "common coastal protein",
      cuisines: ["Mexican"],
      vegan: false,
      amount: 35.0,
      servingSize: "100g",
    },
    {
      name: "Seaweed (increasingly available)",
      reason: "growing availability",
      cuisines: ["Mexican"],
      vegan: true,
      amount: 28.0,
      servingSize: "1 sheet nori",
    },
    {
      name: "Shrimp/fish",
      reason: "common coastal protein",
      cuisines: ["Cuban / Caribbean"],
      vegan: false,
      amount: 67.5,
      servingSize: "100g",
    },
    {
      name: "Dairy",
      reason: "common source",
      cuisines: ["Cuban / Caribbean"],
      vegan: false,
      amount: 60.0,
      servingSize: "1 cup",
    },
    {
      name: "Dried/smoked fish",
      reason: "common soup addition",
      cuisines: ["West African"],
      vegan: false,
      amount: 62.5,
      servingSize: "50g",
    },
    {
      name: "Seaweed/algae (regionally variable)",
      reason: "less traditional - rely more on iodized salt and fish",
      cuisines: ["West African"],
      vegan: true,
      servingSize: "n/a",
    },
    {
      name: "Nile perch/tilapia",
      reason: "regional fish staple",
      cuisines: ["East African"],
      vegan: false,
      amount: 75.0,
      servingSize: "100g",
    },
    {
      name: "Dairy (ergo)",
      reason: "traditional fermented dairy",
      cuisines: ["East African"],
      vegan: false,
      amount: 60.0,
      servingSize: "1 cup",
    },
    {
      name: "Yogurt/dairy",
      reason: "daily staple",
      cuisines: ["South Asian (Indian)"],
      vegan: false,
      amount: 60.0,
      servingSize: "1 cup",
    },
    {
      name: "Fish (coastal regions)",
      reason: "where regionally available",
      cuisines: ["South Asian (Indian)"],
      vegan: false,
      amount: 100.0,
      servingSize: "100g",
    },
    {
      name: "Fish sauce / small fish",
      reason: "common regional flavour base",
      cuisines: ["Southeast Asian"],
      vegan: false,
      amount: 30.0,
      servingSize: "1 serving",
    },
    {
      name: "Seaweed",
      reason: "common in Filipino/Vietnamese dishes",
      cuisines: ["Southeast Asian"],
      vegan: true,
      amount: 28.0,
      servingSize: "1 sheet nori",
    },
    {
      name: "Seaweed (kombu, nori, wakame)",
      reason: "traditional and highly reliable source - moderate intake due to high potency",
      cuisines: ["East Asian"],
      vegan: true,
      servingSize: "1 sheet/serving",
    },
    {
      name: "Fish/shellfish",
      reason: "common regional protein",
      cuisines: ["East Asian"],
      vegan: false,
      amount: 100.0,
      servingSize: "100g",
    },
    {
      name: "Yogurt/labneh",
      reason: "daily staple",
      cuisines: ["Middle Eastern"],
      vegan: false,
      amount: 50.0,
      servingSize: "1/2 cup",
    },
    {
      name: "Cod or other whitefish",
      reason: "widely available",
      vegan: false,
      amount: 125.0,
      servingSize: "100g",
    },
    {
      name: "Nori, dried",
      reason: "reliable, culinary-scale safe — a few sheets a week covers meaningful ground",
      cuisines: ["East Asian"],
      vegan: true,
      servingSize: "5g sheet",
    },
    {
      name: "Wakame, dried",
      reason: "soups, miso, grain bowls",
      cuisines: ["East Asian"],
      vegan: true,
      amount: 90.0,
      servingSize: "10g",
    },
    {
      name: "Dulse, dried",
      reason: "flakes work well as a seasoning",
      cuisines: ["Irish / Maritime Canadian"],
      vegan: true,
      servingSize: "10g",
    },
    {
      name: "Kombu, dried",
      reason: "broth base only — discard before eating, extremely concentrated",
      cuisines: ["East Asian"],
      vegan: true,
      amount: 1.0,
      servingSize: "1g",
    },
    {
      name: "Iodized salt or 150mcg potassium iodide supplement",
      reason:
        "reasonable baseline for anyone not eating seaweed regularly; flag caution for Hashimoto's patients",
      vegan: true,
      amount: 71.0,
      servingSize: "1/4 tsp / as directed",
    },
  ],
  zinc: [
    {
      name: "Pumpkin seeds",
      reason: "snack, granola mix-in",
      cuisines: ["Canadian / North American"],
      vegan: true,
      amount: 2.2,
      servingSize: "1 oz",
    },
    {
      name: "Beef",
      reason: "common protein source",
      cuisines: ["Canadian / North American"],
      vegan: false,
      amount: 4.8,
      servingSize: "100g",
    },
    {
      name: "Fortified cereal",
      reason: "breakfast staple",
      cuisines: ["Canadian / North American"],
      vegan: true,
      amount: 4.0,
      servingSize: "1 cup",
    },
    {
      name: "Sunflower seeds",
      reason: "common snack",
      cuisines: ["Ukrainian / Eastern European"],
      vegan: true,
      amount: 1.5,
      servingSize: "1 oz",
    },
    {
      name: "Beef (traditional stews)",
      reason: "common protein",
      cuisines: ["Ukrainian / Eastern European"],
      vegan: false,
      amount: 4.8,
      servingSize: "100g",
    },
    {
      name: "Buckwheat",
      reason: "daily staple grain",
      cuisines: ["Ukrainian / Eastern European"],
      vegan: true,
      amount: 1.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Chickpeas",
      reason: "pasta e ceci",
      cuisines: ["Italian"],
      vegan: true,
      amount: 2.5,
      servingSize: "1 cup cooked",
    },
    {
      name: "Parmesan cheese",
      reason: "widely used topping",
      cuisines: ["Italian"],
      vegan: false,
      amount: 1.0,
      servingSize: "1 oz",
    },
    {
      name: "Clams/mussels",
      reason: "coastal staple, very high in clams",
      cuisines: ["Italian"],
      vegan: false,
      amount: 7.3,
      servingSize: "100g",
    },
    {
      name: "Clams (almejas)",
      reason: "coastal staple, extremely zinc-dense",
      cuisines: ["Spanish / Mediterranean"],
      vegan: false,
      amount: 13.0,
      servingSize: "100g",
    },
    {
      name: "Pepitas (pumpkin seeds)",
      reason: "snack, mole ingredient",
      cuisines: ["Mexican"],
      vegan: true,
      amount: 2.2,
      servingSize: "1 oz",
    },
    {
      name: "Black beans",
      reason: "daily staple",
      cuisines: ["Mexican"],
      vegan: true,
      amount: 1.9,
      servingSize: "1 cup cooked",
    },
    {
      name: "Beef (carne asada, in moderation)",
      reason: "common protein",
      cuisines: ["Mexican"],
      vegan: false,
      amount: 4.8,
      servingSize: "100g",
    },
    {
      name: "Pork (traditional, in moderation)",
      reason: "common protein",
      cuisines: ["Cuban / Caribbean"],
      vegan: false,
      amount: 2.9,
      servingSize: "100g",
    },
    {
      name: "Pumpkin (calabaza) seeds",
      reason: "common snack",
      cuisines: ["Cuban / Caribbean"],
      vegan: true,
      amount: 2.2,
      servingSize: "1 oz",
    },
    {
      name: "Egusi (melon seeds)",
      reason: "staple soup base",
      cuisines: ["West African"],
      vegan: true,
      amount: 2.5,
      servingSize: "1/2 cup",
    },
    {
      name: "Black-eyed peas",
      reason: "common legume",
      cuisines: ["West African"],
      vegan: true,
      amount: 2.2,
      servingSize: "1 cup cooked",
    },
    {
      name: "Goat meat",
      reason: "traditional protein",
      cuisines: ["West African"],
      vegan: false,
      amount: 4.0,
      servingSize: "100g",
    },
    {
      name: "Lentils (misir)",
      reason: "staple stew",
      cuisines: ["East African"],
      vegan: true,
      amount: 2.5,
      servingSize: "1 cup cooked",
    },
    {
      name: "Teff",
      reason: "daily staple grain",
      cuisines: ["East African"],
      vegan: true,
      amount: 2.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Goat/beef (in moderation)",
      reason: "traditional protein",
      cuisines: ["East African"],
      vegan: false,
      amount: 4.4,
      servingSize: "100g",
    },
    {
      name: "Chickpeas (chana)",
      reason: "chana masala",
      cuisines: ["South Asian (Indian)"],
      vegan: true,
      amount: 2.5,
      servingSize: "1 cup cooked",
    },
    {
      name: "Paneer/dairy",
      reason: "vegetarian protein staple",
      cuisines: ["South Asian (Indian)"],
      vegan: false,
      amount: 1.0,
      servingSize: "1/2 cup",
    },
    {
      name: "Shrimp",
      reason: "common regional protein",
      cuisines: ["Southeast Asian"],
      vegan: false,
      amount: 1.6,
      servingSize: "100g",
    },
    {
      name: "Mung beans",
      reason: "common legume",
      cuisines: ["Southeast Asian"],
      vegan: true,
      amount: 1.7,
      servingSize: "1 cup cooked",
    },
    {
      name: "Tofu, firm",
      reason: "common protein base",
      cuisines: ["Southeast Asian"],
      vegan: true,
      amount: 1.5,
      servingSize: "1/2 cup",
    },
    {
      name: "Oysters",
      reason: "traditional and extremely zinc-dense",
      cuisines: ["East Asian"],
      vegan: false,
      amount: 16.0,
      servingSize: "3-4 medium",
    },
    {
      name: "Tofu",
      reason: "daily staple protein",
      cuisines: ["East Asian"],
      vegan: true,
      amount: 1.5,
      servingSize: "1/2 cup",
    },
    {
      name: "Edamame",
      reason: "common side dish",
      cuisines: ["East Asian"],
      vegan: true,
      amount: 2.5,
      servingSize: "1 cup",
    },
    {
      name: "Chickpeas (hummus)",
      reason: "daily staple",
      cuisines: ["Middle Eastern"],
      vegan: true,
      amount: 1.3,
      servingSize: "1/2 cup",
    },
    {
      name: "Tahini",
      reason: "common condiment",
      cuisines: ["Middle Eastern"],
      vegan: true,
      amount: 1.4,
      servingSize: "2 tbsp",
    },
    {
      name: "Lamb",
      reason: "traditional protein source",
      cuisines: ["Middle Eastern"],
      vegan: false,
      amount: 4.0,
      servingSize: "100g",
    },
    {
      name: "Beef (where culturally appropriate)",
      reason: "widely available",
      vegan: false,
      amount: 4.8,
      servingSize: "100g",
    },
    {
      name: "Hemp seeds",
      reason: "also omega-3, complete protein",
      cuisines: ["Canadian / North American", "Ukrainian / Eastern European"],
      vegan: true,
      amount: 3.0,
      servingSize: "3 tbsp",
    },
    {
      name: "Chickpeas, cooked",
      reason: "soak 8-12 hrs first to reduce phytates by 47-56%",
      cuisines: ["Middle Eastern", "South Asian (Indian)", "Spanish / Mediterranean"],
      vegan: true,
      amount: 2.5,
      servingSize: "1 cup",
    },
    {
      name: "Lentils, cooked",
      reason: "soak before cooking for the same reason",
      cuisines: [
        "South Asian (Indian)",
        "Middle Eastern",
        "Spanish / Mediterranean",
        "Ukrainian / Eastern European",
      ],
      vegan: true,
      amount: 2.5,
      servingSize: "1 cup",
    },
    {
      name: "Quinoa, cooked",
      reason: "also complete protein",
      cuisines: ["Andean / South American"],
      vegan: true,
      amount: 2.0,
      servingSize: "1 cup",
    },
    {
      name: "Black beans, cooked",
      reason: "also magnesium, folate",
      cuisines: ["Mexican", "Cuban / Caribbean"],
      vegan: true,
      amount: 1.9,
      servingSize: "1 cup",
    },
    {
      name: "Tempeh",
      reason:
        "fermented — best bioavailability of any plant zinc source (up to 92% fractional absorption)",
      cuisines: ["Southeast Asian"],
      vegan: true,
      amount: 1.9,
      servingSize: "1/2 cup",
    },
    {
      name: "Cashews",
      reason: "also magnesium 75mg",
      vegan: true,
      amount: 1.6,
      servingSize: "1 oz",
    },
  ],
  choline: [
    {
      name: "Eggs",
      reason: "breakfast staple",
      cuisines: ["Canadian / North American"],
      vegan: false,
      amount: 294.0,
      servingSize: "2 whole",
    },
    {
      name: "Soybeans/edamame",
      reason: "common protein source",
      cuisines: ["Canadian / North American"],
      vegan: true,
      amount: 107.0,
      servingSize: "1 cup",
    },
    {
      name: "Chicken breast",
      reason: "common protein",
      cuisines: ["Canadian / North American"],
      vegan: false,
      amount: 72.0,
      servingSize: "100g",
    },
    {
      name: "Beef liver",
      reason: "traditional organ meat use",
      cuisines: ["Ukrainian / Eastern European"],
      vegan: false,
      amount: 213.0,
      servingSize: "50g",
    },
    {
      name: "Kefir/dairy",
      reason: "daily staple",
      cuisines: ["Ukrainian / Eastern European"],
      vegan: false,
      amount: 40.0,
      servingSize: "1 cup",
    },
    {
      name: "Chickpeas",
      reason: "pasta e ceci",
      cuisines: ["Italian"],
      vegan: true,
      amount: 70.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Cuttlefish/squid",
      reason: "common coastal seafood",
      cuisines: ["Italian"],
      vegan: false,
      amount: 65.0,
      servingSize: "100g",
    },
    {
      name: "Octopus/squid",
      reason: "common regional seafood",
      cuisines: ["Spanish / Mediterranean"],
      vegan: false,
      amount: 65.0,
      servingSize: "100g",
    },
    {
      name: "Black beans",
      reason: "daily staple",
      cuisines: ["Mexican"],
      vegan: true,
      amount: 88.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Shrimp",
      reason: "common coastal protein",
      cuisines: ["Mexican"],
      vegan: false,
      amount: 70.0,
      servingSize: "100g",
    },
    {
      name: "Shrimp/fish",
      reason: "common coastal protein",
      cuisines: ["Cuban / Caribbean"],
      vegan: false,
      amount: 70.0,
      servingSize: "100g",
    },
    {
      name: "Black-eyed peas",
      reason: "common legume",
      cuisines: ["West African"],
      vegan: true,
      amount: 90.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Egusi seeds",
      reason: "staple soup base",
      cuisines: ["West African"],
      vegan: true,
      amount: 60.0,
      servingSize: "1/2 cup",
    },
    {
      name: "Lentils (misir)",
      reason: "traditional staple stew",
      cuisines: ["East African"],
      vegan: true,
      amount: 128.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Mushrooms (where available)",
      reason: "growing availability",
      cuisines: ["East African"],
      vegan: true,
      amount: 58.0,
      servingSize: "1/2 cup",
    },
    {
      name: "Chickpeas (chana)",
      reason: "chana masala",
      cuisines: ["South Asian (Indian)"],
      vegan: true,
      amount: 70.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Paneer/dairy",
      reason: "common vegetarian protein",
      cuisines: ["South Asian (Indian)"],
      vegan: false,
      amount: 20.0,
      servingSize: "1/2 cup",
    },
    {
      name: "Tofu",
      reason: "common protein base",
      cuisines: ["Southeast Asian"],
      vegan: true,
      amount: 38.0,
      servingSize: "1/2 cup",
    },
    {
      name: "Shiitake mushrooms",
      reason: "common umami base",
      cuisines: ["East Asian"],
      vegan: true,
      amount: 58.0,
      servingSize: "1/2 cup",
    },
    {
      name: "Tofu/edamame",
      reason: "daily staple protein",
      cuisines: ["East Asian"],
      vegan: true,
      amount: 45.5,
      servingSize: "1/2 cup",
    },
    {
      name: "Chickpeas (hummus)",
      reason: "daily staple",
      cuisines: ["Middle Eastern"],
      vegan: true,
      amount: 35.0,
      servingSize: "1/2 cup",
    },
    {
      name: "Lamb",
      reason: "traditional protein source",
      cuisines: ["Middle Eastern"],
      vegan: false,
      amount: 80.0,
      servingSize: "100g",
    },
    {
      name: "Soybeans / edamame, cooked",
      reason: "highest plant choline source in the guide",
      cuisines: ["East Asian"],
      vegan: true,
      amount: 107.0,
      servingSize: "1 cup",
    },
    {
      name: "Broccoli, cooked",
      reason: "common everyday contributor",
      cuisines: ["Italian", "Canadian / North American"],
      vegan: true,
      amount: 63.0,
      servingSize: "1 cup",
    },
    {
      name: "Brussels sprouts, cooked",
      reason: "common everyday contributor",
      cuisines: ["Ukrainian / Eastern European", "Canadian / North American"],
      vegan: true,
      amount: 63.0,
      servingSize: "1 cup",
    },
    {
      name: "Tempeh",
      reason: "fermented soy",
      cuisines: ["Southeast Asian"],
      vegan: true,
      amount: 58.0,
      servingSize: "1/2 cup",
    },
    {
      name: "Kidney beans, cooked",
      reason: "everyday legume",
      cuisines: ["Canadian / North American", "South Asian (Indian)", "Andean / South American"],
      vegan: true,
      amount: 54.0,
      servingSize: "1 cup",
    },
    {
      name: "Sunflower seeds",
      reason: "named alongside chickpeas as the choline load in the roasted chickpea bowl",
      cuisines: ["Ukrainian / Eastern European", "Canadian / North American"],
      vegan: true,
      servingSize: "2 tbsp",
    },
    {
      name: "Quinoa, cooked",
      reason: "also complete protein",
      cuisines: ["Andean / South American"],
      vegan: true,
      amount: 43.0,
      servingSize: "1 cup",
    },
    {
      name: "Betaine-rich foods: beets, spinach, quinoa, whole grains",
      reason:
        "betaine-homocysteine methyltransferase pathway provides ~50% of methylation support and partially offsets choline need",
      vegan: true,
      servingSize: "varies",
    },
  ],
  magnesium: [
    {
      name: "Pumpkin seeds",
      reason: "snack, granola mix-in",
      cuisines: ["Canadian / North American"],
      vegan: true,
      amount: 150.0,
      servingSize: "1 oz",
    },
    {
      name: "Black beans",
      reason: "common legume",
      cuisines: ["Canadian / North American"],
      vegan: true,
      amount: 120.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Dark chocolate (70%+)",
      reason: "widely available treat",
      cuisines: ["Canadian / North American"],
      vegan: true,
      amount: 65.0,
      servingSize: "1 oz",
    },
    {
      name: "Buckwheat",
      reason: "daily staple grain",
      cuisines: ["Ukrainian / Eastern European"],
      vegan: true,
      amount: 86.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Sunflower seeds",
      reason: "common snack",
      cuisines: ["Ukrainian / Eastern European"],
      vegan: true,
      amount: 37.0,
      servingSize: "1 oz",
    },
    {
      name: "Poppy seeds",
      reason: "traditional baking ingredient",
      cuisines: ["Ukrainian / Eastern European"],
      vegan: true,
      amount: 60.0,
      servingSize: "2 tbsp",
    },
    {
      name: "White beans",
      reason: "common legume",
      cuisines: ["Italian"],
      vegan: true,
      amount: 134.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Farro",
      reason: "traditional grain",
      cuisines: ["Italian"],
      vegan: true,
      amount: 60.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Pistachios",
      reason: "sicilian staple nut",
      cuisines: ["Italian"],
      vegan: true,
      amount: 34.0,
      servingSize: "1 oz",
    },
    {
      name: "Almonds",
      reason: "common snack, marcona almonds",
      cuisines: ["Spanish / Mediterranean"],
      vegan: true,
      amount: 76.0,
      servingSize: "1 oz",
    },
    {
      name: "Chickpeas",
      reason: "cocido",
      cuisines: ["Spanish / Mediterranean"],
      vegan: true,
      amount: 80.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Swiss chard (acelgas)",
      reason: "traditional green",
      cuisines: ["Spanish / Mediterranean"],
      vegan: true,
      amount: 150.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Pepitas (pumpkin seeds)",
      reason: "snack, mole ingredient",
      cuisines: ["Mexican"],
      vegan: true,
      amount: 150.0,
      servingSize: "1 oz",
    },
    {
      name: "Avocado",
      reason: "common topping, not excluded",
      cuisines: ["Mexican"],
      vegan: true,
      amount: 29.0,
      servingSize: "1/2 fruit",
    },
    {
      name: "Plantain",
      reason: "daily staple starch",
      cuisines: ["Cuban / Caribbean"],
      vegan: true,
      amount: 49.0,
      servingSize: "1 medium",
    },
    {
      name: "Okra",
      reason: "common stew vegetable",
      cuisines: ["Cuban / Caribbean"],
      vegan: true,
      amount: 94.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Black-eyed peas",
      reason: "common legume",
      cuisines: ["West African"],
      vegan: true,
      amount: 92.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Egusi seeds",
      reason: "staple soup base",
      cuisines: ["West African"],
      vegan: true,
      amount: 100.0,
      servingSize: "1/2 cup",
    },
    {
      name: "Millet",
      reason: "common grain",
      cuisines: ["West African"],
      vegan: true,
      amount: 76.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Teff",
      reason: "notably high-magnesium grain",
      cuisines: ["East African"],
      vegan: true,
      amount: 178.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Lentils",
      reason: "common staple",
      cuisines: ["East African"],
      vegan: true,
      amount: 71.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Collard greens",
      reason: "traditional side",
      cuisines: ["East African"],
      vegan: true,
      amount: 50.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Moong dal",
      reason: "daily staple dal",
      cuisines: ["South Asian (Indian)"],
      vegan: true,
      amount: 80.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Ragi (finger millet)",
      reason: "south Indian staple",
      cuisines: ["South Asian (Indian)"],
      vegan: true,
      amount: 137.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Almonds (badam)",
      reason: "common snack",
      cuisines: ["South Asian (Indian)"],
      vegan: true,
      amount: 76.0,
      servingSize: "1 oz",
    },
    {
      name: "Mung beans",
      reason: "common legume",
      cuisines: ["Southeast Asian"],
      vegan: true,
      amount: 97.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Tofu",
      reason: "common protein base",
      cuisines: ["Southeast Asian"],
      vegan: true,
      amount: 37.0,
      servingSize: "1/2 cup",
    },
    {
      name: "Water spinach",
      reason: "common green",
      cuisines: ["Southeast Asian"],
      vegan: true,
      amount: 50.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Edamame",
      reason: "common side dish",
      cuisines: ["East Asian"],
      vegan: true,
      amount: 100.0,
      servingSize: "1 cup",
    },
    {
      name: "Seaweed (wakame)",
      reason: "common in soups and salads",
      cuisines: ["East Asian"],
      vegan: true,
      amount: 40.0,
      servingSize: "1/2 cup",
    },
    {
      name: "Tahini",
      reason: "common condiment",
      cuisines: ["Middle Eastern"],
      vegan: true,
      amount: 30.0,
      servingSize: "2 tbsp",
    },
    {
      name: "Chickpeas (hummus)",
      reason: "daily staple",
      cuisines: ["Middle Eastern"],
      vegan: true,
      amount: 40.0,
      servingSize: "1/2 cup",
    },
    {
      name: "Hemp seeds",
      reason: "also complete protein and omega-3",
      cuisines: ["Canadian / North American", "Ukrainian / Eastern European"],
      vegan: true,
      amount: 210.0,
      servingSize: "3 tbsp",
    },
    {
      name: "Spinach, cooked",
      reason: "also iron, folate",
      vegan: true,
      amount: 157.0,
      servingSize: "1 cup",
    },
    {
      name: "Black beans, cooked",
      reason: "also iron, protein, folate",
      cuisines: ["Mexican", "Cuban / Caribbean"],
      vegan: true,
      amount: 120.0,
      servingSize: "1 cup",
    },
    {
      name: "Quinoa, cooked",
      reason: "also complete protein",
      cuisines: ["Andean / South American"],
      vegan: true,
      amount: 118.0,
      servingSize: "1 cup",
    },
    {
      name: "Brown rice, cooked",
      reason: "also B6",
      cuisines: ["East Asian", "South Asian (Indian)"],
      vegan: true,
      amount: 84.0,
      servingSize: "1 cup",
    },
    {
      name: "Dark chocolate, 70%+",
      reason: "also iron 3.4mg",
      cuisines: ["West African", "Andean / South American"],
      vegan: true,
      amount: 64.0,
      servingSize: "1 oz",
    },
    {
      name: "Tofu, firm",
      reason: "also calcium, protein, iron",
      cuisines: ["East Asian"],
      vegan: true,
      amount: 53.0,
      servingSize: "1/2 cup",
    },
    {
      name: "Banana",
      reason: "also B6, potassium",
      cuisines: ["Cuban / Caribbean", "East African"],
      vegan: true,
      amount: 32.0,
      servingSize: "1 medium",
    },
  ],
  folate: [
    {
      name: "Fortified bread/pasta",
      reason: "canadian flour is folate-fortified by law",
      cuisines: ["Canadian / North American"],
      vegan: true,
      amount: 80.0,
      servingSize: "1 serving",
    },
    {
      name: "Lentils",
      reason: "soups, staple legume",
      cuisines: ["Canadian / North American"],
      vegan: true,
      amount: 358.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Asparagus",
      reason: "common seasonal vegetable",
      cuisines: ["Canadian / North American"],
      vegan: true,
      amount: 260.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Beets and beet greens",
      reason: "borscht base",
      cuisines: ["Ukrainian / Eastern European"],
      vegan: true,
      amount: 150.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Buckwheat",
      reason: "daily staple grain",
      cuisines: ["Ukrainian / Eastern European"],
      vegan: true,
      amount: 65.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Sunflower seeds",
      reason: "common snack",
      cuisines: ["Ukrainian / Eastern European"],
      vegan: true,
      amount: 80.0,
      servingSize: "1 oz",
    },
    {
      name: "White beans",
      reason: "minestrone, pasta e fagioli",
      cuisines: ["Italian"],
      vegan: true,
      amount: 255.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Broccoli rabe (rapini)",
      reason: "traditional Southern Italian green",
      cuisines: ["Italian"],
      vegan: true,
      amount: 170.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Chickpeas",
      reason: "pasta e ceci",
      cuisines: ["Italian"],
      vegan: true,
      amount: 280.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Spinach",
      reason: "espinacas con garbanzos",
      cuisines: ["Spanish / Mediterranean"],
      vegan: true,
      amount: 260.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Oranges",
      reason: "common fruit, also vitamin C pairing",
      cuisines: ["Spanish / Mediterranean"],
      vegan: true,
      amount: 40.0,
      servingSize: "1 medium",
    },
    {
      name: "Black beans",
      reason: "daily staple",
      cuisines: ["Mexican"],
      vegan: true,
      amount: 256.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Corn tortillas (fortified in some regions)",
      reason: "staple starch",
      cuisines: ["Mexican"],
      vegan: true,
      amount: 50.0,
      servingSize: "2 tortillas",
    },
    {
      name: "Avocado",
      reason: "common topping, not excluded",
      cuisines: ["Mexican"],
      vegan: true,
      amount: 60.0,
      servingSize: "1/2 fruit",
    },
    {
      name: "Okra",
      reason: "common stew vegetable",
      cuisines: ["Cuban / Caribbean"],
      vegan: true,
      amount: 130.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Plantain",
      reason: "daily staple starch",
      cuisines: ["Cuban / Caribbean"],
      vegan: true,
      amount: 35.0,
      servingSize: "1 medium",
    },
    {
      name: "Black-eyed peas",
      reason: "common stew legume",
      cuisines: ["West African"],
      vegan: true,
      amount: 356.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Bitter leaf/greens",
      reason: "traditional leafy green",
      cuisines: ["West African"],
      vegan: true,
      amount: 100.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Lentils (misir)",
      reason: "ethiopian staple stew",
      cuisines: ["East African"],
      vegan: true,
      amount: 358.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Collard greens (gomen)",
      reason: "traditional side dish",
      cuisines: ["East African"],
      vegan: true,
      amount: 175.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Chickpeas (shiro base)",
      reason: "common stew base",
      cuisines: ["East African"],
      vegan: true,
      amount: 280.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Moong dal",
      reason: "daily staple dal",
      cuisines: ["South Asian (Indian)"],
      vegan: true,
      amount: 80.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Spinach (palak)",
      reason: "palak paneer, saag",
      cuisines: ["South Asian (Indian)"],
      vegan: true,
      amount: 260.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Chickpeas (chana)",
      reason: "chana masala",
      cuisines: ["South Asian (Indian)"],
      vegan: true,
      amount: 280.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Mung beans",
      reason: "sweet and savoury dishes",
      cuisines: ["Southeast Asian"],
      vegan: true,
      amount: 320.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Water spinach",
      reason: "common stir-fry green",
      cuisines: ["Southeast Asian"],
      vegan: true,
      amount: 100.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Edamame",
      reason: "common side dish",
      cuisines: ["Southeast Asian"],
      vegan: true,
      amount: 482.0,
      servingSize: "1 cup",
    },
    {
      name: "Bok choy",
      reason: "common green",
      cuisines: ["East Asian"],
      vegan: true,
      amount: 70.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Seaweed (various)",
      reason: "common in soups",
      cuisines: ["East Asian"],
      vegan: true,
      amount: 75.0,
      servingSize: "1 serving",
    },
    {
      name: "Lentils (mujadara)",
      reason: "staple dish",
      cuisines: ["Middle Eastern"],
      vegan: true,
      amount: 358.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Chickpeas (hummus)",
      reason: "daily staple",
      cuisines: ["Middle Eastern"],
      vegan: true,
      amount: 140.0,
      servingSize: "1/2 cup",
    },
    {
      name: "Parsley (tabbouleh)",
      reason: "traditional herb-forward salad",
      cuisines: ["Middle Eastern"],
      vegan: true,
      amount: 50.0,
      servingSize: "1 cup",
    },
    {
      name: "Fortified grains (where available)",
      reason: "common in North America and parts of Europe",
      vegan: true,
      amount: 80.0,
      servingSize: "1 serving",
    },
    {
      name: "Lentils, cooked",
      reason: "highest folate source in the guide's iron table",
      cuisines: [
        "South Asian (Indian)",
        "Middle Eastern",
        "Spanish / Mediterranean",
        "Ukrainian / Eastern European",
      ],
      vegan: true,
      amount: 358.0,
      servingSize: "1 cup",
    },
    {
      name: "Black beans, cooked",
      reason: "also iron, fibre",
      cuisines: ["Mexican", "Cuban / Caribbean"],
      vegan: true,
      amount: 256.0,
      servingSize: "1 cup",
    },
    {
      name: "Kidney beans, cooked",
      reason: "also iron, fibre",
      cuisines: ["Canadian / North American", "South Asian (Indian)", "Andean / South American"],
      vegan: true,
      amount: 230.0,
      servingSize: "1 cup",
    },
    {
      name: "Spinach, cooked",
      reason: "also iron, magnesium",
      vegan: true,
      amount: 131.0,
      servingSize: "1/2 cup",
    },
    {
      name: "Quinoa, cooked",
      reason: "highest-folate whole grain in the grain comparison table",
      cuisines: ["Andean / South American"],
      vegan: true,
      amount: 78.0,
      servingSize: "1 cup",
    },
    {
      name: "Amaranth, cooked",
      reason: "also highest magnesium of the grains listed",
      cuisines: ["Mexican", "East African"],
      vegan: true,
      amount: 54.0,
      servingSize: "1 cup",
    },
    {
      name: "Rye, cooked",
      reason: "also top fibre grain in the table",
      cuisines: ["Ukrainian / Eastern European"],
      vegan: true,
      amount: 38.0,
      servingSize: "1 cup",
    },
  ],
  vitamin_b6: [
    {
      name: "Chickpeas",
      reason: "hummus, salads",
      cuisines: ["Canadian / North American"],
      vegan: true,
      amount: 1.1,
      servingSize: "1 cup cooked",
    },
    {
      name: "Banana",
      reason: "common everyday fruit",
      cuisines: ["Canadian / North American"],
      vegan: true,
      amount: 0.4,
      servingSize: "1 medium",
    },
    {
      name: "Potato with skin",
      reason: "everyday staple",
      cuisines: ["Canadian / North American"],
      vegan: true,
      amount: 0.4,
      servingSize: "1 medium",
    },
    {
      name: "Buckwheat",
      reason: "daily staple grain",
      cuisines: ["Ukrainian / Eastern European"],
      vegan: true,
      amount: 0.2,
      servingSize: "1 cup cooked",
    },
    {
      name: "Sunflower seeds",
      reason: "common snack",
      cuisines: ["Ukrainian / Eastern European"],
      vegan: true,
      amount: 0.2,
      servingSize: "1 oz",
    },
    {
      name: "Tuna",
      reason: "common pantry fish",
      cuisines: ["Italian"],
      vegan: false,
      amount: 0.9,
      servingSize: "100g",
    },
    {
      name: "Pistachios",
      reason: "sicilian staple nut",
      cuisines: ["Italian"],
      vegan: true,
      amount: 0.3,
      servingSize: "1 oz",
    },
    {
      name: "Tuna/bonito",
      reason: "common regional fish",
      cuisines: ["Spanish / Mediterranean"],
      vegan: false,
      amount: 0.9,
      servingSize: "100g",
    },
    {
      name: "Avocado",
      reason: "everyday staple, not excluded",
      cuisines: ["Mexican"],
      vegan: true,
      amount: 0.2,
      servingSize: "1/2 fruit",
    },
    {
      name: "Plantain/banana",
      reason: "common fruit",
      cuisines: ["Mexican"],
      vegan: true,
      amount: 0.4,
      servingSize: "1 medium",
    },
    {
      name: "Black beans",
      reason: "daily staple",
      cuisines: ["Mexican"],
      vegan: true,
      amount: 0.2,
      servingSize: "1 cup cooked",
    },
    {
      name: "Plantain",
      reason: "daily staple starch",
      cuisines: ["Cuban / Caribbean"],
      vegan: true,
      amount: 0.3,
      servingSize: "1 medium",
    },
    {
      name: "Sweet potato (boniato)",
      reason: "common side",
      cuisines: ["Cuban / Caribbean"],
      vegan: true,
      amount: 0.6,
      servingSize: "1 medium",
    },
    {
      name: "Sweet potato",
      reason: "common staple",
      cuisines: ["West African"],
      vegan: true,
      amount: 0.6,
      servingSize: "1 medium",
    },
    {
      name: "Yam",
      reason: "regional staple starch",
      cuisines: ["West African"],
      vegan: true,
      amount: 0.3,
      servingSize: "1 cup cooked",
    },
    {
      name: "Banana (matoke)",
      reason: "ugandan/regional staple",
      cuisines: ["East African"],
      vegan: true,
      amount: 0.4,
      servingSize: "1 cup cooked",
    },
    {
      name: "Chickpeas (shiro)",
      reason: "common stew base",
      cuisines: ["East African"],
      vegan: true,
      amount: 1.1,
      servingSize: "1 cup cooked",
    },
    {
      name: "Chickpeas (chana)",
      reason: "chana masala",
      cuisines: ["South Asian (Indian)"],
      vegan: true,
      amount: 1.1,
      servingSize: "1 cup cooked",
    },
    {
      name: "Potato",
      reason: "aloo dishes, daily staple",
      cuisines: ["South Asian (Indian)"],
      vegan: true,
      amount: 0.4,
      servingSize: "1 medium",
    },
    {
      name: "Banana (saba/plantain)",
      reason: "common fruit, used in savoury and sweet dishes",
      cuisines: ["Southeast Asian"],
      vegan: true,
      amount: 0.4,
      servingSize: "1 medium",
    },
    {
      name: "Tuna/mackerel",
      reason: "common regional fish",
      cuisines: ["Southeast Asian"],
      vegan: false,
      amount: 0.9,
      servingSize: "100g",
    },
    {
      name: "Tuna/salmon",
      reason: "common regional fish",
      cuisines: ["East Asian"],
      vegan: false,
      amount: 0.9,
      servingSize: "100g",
    },
    {
      name: "Chickpeas/soy-based dishes",
      reason: "increasingly common",
      cuisines: ["East Asian"],
      vegan: true,
      amount: 1.1,
      servingSize: "1 cup cooked",
    },
    {
      name: "Chickpeas (hummus)",
      reason: "daily staple",
      cuisines: ["Middle Eastern"],
      vegan: true,
      amount: 0.6,
      servingSize: "1/2 cup",
    },
    {
      name: "Tahini",
      reason: "common condiment",
      cuisines: ["Middle Eastern"],
      vegan: true,
      amount: 0.2,
      servingSize: "2 tbsp",
    },
    {
      name: "Dates",
      reason: "common snack",
      cuisines: ["Middle Eastern"],
      vegan: true,
      amount: 0.1,
      servingSize: "3 dates",
    },
    {
      name: "Chickpeas, cooked",
      reason: "~85% of daily RDA in a single serving — the standout plant source",
      cuisines: ["Middle Eastern", "South Asian (Indian)", "Spanish / Mediterranean"],
      vegan: true,
      amount: 1.1,
      servingSize: "1 cup",
    },
    {
      name: "Potato, with skin",
      reason: "also potassium, iron",
      cuisines: [
        "Andean / South American",
        "Ukrainian / Eastern European",
        "Canadian / North American",
      ],
      vegan: true,
      amount: 0.7,
      servingSize: "1 medium",
    },
    {
      name: "Spinach, cooked",
      reason: "also iron, magnesium, folate",
      vegan: true,
      amount: 0.44,
      servingSize: "1 cup",
    },
    {
      name: "Brown rice, cooked",
      reason: "also magnesium",
      cuisines: ["East Asian", "South Asian (Indian)"],
      vegan: true,
      amount: 0.28,
      servingSize: "1 cup",
    },
    {
      name: "Prunes",
      reason: "also potassium, iron",
      cuisines: [
        "Ukrainian / Eastern European",
        "Spanish / Mediterranean",
        "Canadian / North American",
      ],
      vegan: true,
      amount: 0.26,
      servingSize: "5 pieces",
    },
  ],
  potassium: [
    {
      name: "Potato with skin",
      reason: "everyday staple",
      cuisines: ["Canadian / North American"],
      vegan: true,
      amount: 900.0,
      servingSize: "1 medium",
    },
    {
      name: "Banana",
      reason: "common everyday fruit",
      cuisines: ["Canadian / North American"],
      vegan: true,
      amount: 420.0,
      servingSize: "1 medium",
    },
    {
      name: "White beans",
      reason: "common legume",
      cuisines: ["Canadian / North American"],
      vegan: true,
      amount: 1000.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Beets",
      reason: "borscht base",
      cuisines: ["Ukrainian / Eastern European"],
      vegan: true,
      amount: 500.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Dried apricots (uzvar)",
      reason: "traditional dried fruit compote",
      cuisines: ["Ukrainian / Eastern European"],
      vegan: true,
      amount: 400.0,
      servingSize: "1/4 cup",
    },
    {
      name: "Tomatoes",
      reason: "sauce base",
      cuisines: ["Italian"],
      vegan: true,
      amount: 430.0,
      servingSize: "1 cup",
    },
    {
      name: "Swiss chard",
      reason: "traditional green",
      cuisines: ["Italian"],
      vegan: true,
      amount: 960.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Potatoes",
      reason: "tortilla espanola",
      cuisines: ["Spanish / Mediterranean"],
      vegan: true,
      amount: 900.0,
      servingSize: "1 medium",
    },
    {
      name: "Swiss chard (acelgas)",
      reason: "traditional side",
      cuisines: ["Spanish / Mediterranean"],
      vegan: true,
      amount: 960.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Black beans",
      reason: "daily staple",
      cuisines: ["Mexican"],
      vegan: true,
      amount: 610.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Avocado",
      reason: "common topping, not excluded",
      cuisines: ["Mexican"],
      vegan: true,
      amount: 487.0,
      servingSize: "1/2 fruit",
    },
    {
      name: "Sweet potato (camote)",
      reason: "common side",
      cuisines: ["Mexican"],
      vegan: true,
      amount: 540.0,
      servingSize: "1 medium",
    },
    {
      name: "Plantain",
      reason: "daily staple starch",
      cuisines: ["Cuban / Caribbean"],
      vegan: true,
      amount: 500.0,
      servingSize: "1 medium",
    },
    {
      name: "Coconut water",
      reason: "common traditional drink",
      cuisines: ["Cuban / Caribbean"],
      vegan: true,
      amount: 600.0,
      servingSize: "1 cup",
    },
    {
      name: "Yam",
      reason: "regional staple starch",
      cuisines: ["West African"],
      vegan: true,
      amount: 900.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Black-eyed peas",
      reason: "common legume",
      cuisines: ["West African"],
      vegan: true,
      amount: 475.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Banana (matoke)",
      reason: "ugandan/regional staple",
      cuisines: ["East African"],
      vegan: true,
      amount: 420.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Lentils",
      reason: "common staple stew",
      cuisines: ["East African"],
      vegan: true,
      amount: 730.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Sweet potato",
      reason: "common side",
      cuisines: ["East African"],
      vegan: true,
      amount: 540.0,
      servingSize: "1 medium",
    },
    {
      name: "Potato (aloo)",
      reason: "daily staple",
      cuisines: ["South Asian (Indian)"],
      vegan: true,
      amount: 900.0,
      servingSize: "1 medium",
    },
    {
      name: "Banana (kela)",
      reason: "common everyday fruit",
      cuisines: ["South Asian (Indian)"],
      vegan: true,
      amount: 420.0,
      servingSize: "1 medium",
    },
    {
      name: "Moong dal",
      reason: "common staple dal",
      cuisines: ["South Asian (Indian)"],
      vegan: true,
      amount: 600.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Banana (saba)",
      reason: "common fruit",
      cuisines: ["Southeast Asian"],
      vegan: true,
      amount: 420.0,
      servingSize: "1 medium",
    },
    {
      name: "Mung beans",
      reason: "common legume",
      cuisines: ["Southeast Asian"],
      vegan: true,
      amount: 530.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Edamame",
      reason: "common side dish",
      cuisines: ["East Asian"],
      vegan: true,
      amount: 676.0,
      servingSize: "1 cup",
    },
    {
      name: "Seaweed (various)",
      reason: "common in soups",
      cuisines: ["East Asian"],
      vegan: true,
      amount: 350.0,
      servingSize: "1 serving",
    },
    {
      name: "Dried apricots",
      reason: "common snack",
      cuisines: ["Middle Eastern"],
      vegan: true,
      amount: 400.0,
      servingSize: "1/4 cup",
    },
    {
      name: "Chickpeas (hummus)",
      reason: "daily staple",
      cuisines: ["Middle Eastern"],
      vegan: true,
      amount: 240.0,
      servingSize: "1/2 cup",
    },
    {
      name: "Dates",
      reason: "common snack",
      cuisines: ["Middle Eastern"],
      vegan: true,
      amount: 270.0,
      servingSize: "3 dates",
    },
    {
      name: "Potato, with skin",
      reason: "also vitamin C 17mg",
      cuisines: [
        "Andean / South American",
        "Ukrainian / Eastern European",
        "Canadian / North American",
      ],
      vegan: true,
      amount: 897.0,
      servingSize: "1 medium",
    },
    {
      name: "Beet greens, cooked",
      reason: "also magnesium 49mg",
      vegan: true,
      amount: 654.0,
      servingSize: "1/2 cup",
    },
    {
      name: "Swiss chard, cooked",
      reason: "also magnesium 75mg",
      vegan: true,
      amount: 483.0,
      servingSize: "1/2 cup",
    },
    {
      name: "Prunes / dried plums",
      reason: "also iron, fibre",
      cuisines: [
        "Ukrainian / Eastern European",
        "Spanish / Mediterranean",
        "Canadian / North American",
      ],
      vegan: true,
      amount: 354.0,
      servingSize: "5 pieces",
    },
    {
      name: "White / navy beans, cooked",
      reason: "everyday legume staple",
      vegan: true,
      servingSize: "1 cup",
    },
  ],
  vitamin_c: [
    {
      name: "Bell peppers",
      reason: "salads, stir-fries",
      cuisines: ["Canadian / North American"],
      vegan: true,
      amount: 150.0,
      servingSize: "1 cup",
    },
    {
      name: "Broccoli",
      reason: "common side vegetable",
      cuisines: ["Canadian / North American"],
      vegan: true,
      amount: 100.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Strawberries",
      reason: "common local fruit in season",
      cuisines: ["Canadian / North American"],
      vegan: true,
      amount: 85.0,
      servingSize: "1 cup",
    },
    {
      name: "Sauerkraut (fermented cabbage)",
      reason: "traditional staple, also supports gut health",
      cuisines: ["Ukrainian / Eastern European"],
      vegan: true,
      amount: 35.0,
      servingSize: "1 cup",
    },
    {
      name: "Bell peppers (roasted)",
      reason: "common in salads and roasted dishes",
      cuisines: ["Ukrainian / Eastern European"],
      vegan: true,
      amount: 150.0,
      servingSize: "1 cup",
    },
    {
      name: "Rosehip tea/syrup",
      reason: "traditional Eastern European remedy",
      cuisines: ["Ukrainian / Eastern European"],
      vegan: true,
      amount: 75.0,
      servingSize: "1 cup",
    },
    {
      name: "Tomatoes",
      reason: "sauce base, pairs with iron-rich legumes",
      cuisines: ["Italian"],
      vegan: true,
      amount: 25.0,
      servingSize: "1 cup",
    },
    {
      name: "Bell peppers (peperoni)",
      reason: "common roasted side",
      cuisines: ["Italian"],
      vegan: true,
      amount: 150.0,
      servingSize: "1 cup",
    },
    {
      name: "Broccoli rabe",
      reason: "traditional Southern Italian green",
      cuisines: ["Italian"],
      vegan: true,
      amount: 65.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Bell peppers (pimientos)",
      reason: "pisto, tapas",
      cuisines: ["Spanish / Mediterranean"],
      vegan: true,
      amount: 150.0,
      servingSize: "1 cup",
    },
    {
      name: "Oranges",
      reason: "common fruit",
      cuisines: ["Spanish / Mediterranean"],
      vegan: true,
      amount: 70.0,
      servingSize: "1 medium",
    },
    {
      name: "Tomatoes (gazpacho base)",
      reason: "traditional cold soup",
      cuisines: ["Spanish / Mediterranean"],
      vegan: true,
      amount: 25.0,
      servingSize: "1 cup",
    },
    {
      name: "Jalapeno/serrano peppers",
      reason: "common seasoning",
      cuisines: ["Mexican"],
      vegan: true,
      amount: 30.0,
      servingSize: "1/4 cup",
    },
    {
      name: "Lime juice",
      reason: "used on nearly every dish",
      cuisines: ["Mexican"],
      vegan: true,
      amount: 18.0,
      servingSize: "2 tbsp",
    },
    {
      name: "Guava",
      reason: "common regional fruit",
      cuisines: ["Mexican"],
      vegan: true,
      amount: 125.0,
      servingSize: "1 fruit",
    },
    {
      name: "Citrus (naranja agria)",
      reason: "common marinade ingredient",
      cuisines: ["Cuban / Caribbean"],
      vegan: true,
      amount: 60.0,
      servingSize: "1 medium",
    },
    {
      name: "Bell peppers/chili peppers",
      reason: "common soup and stew base",
      cuisines: ["West African"],
      vegan: true,
      amount: 150.0,
      servingSize: "1 cup",
    },
    {
      name: "Baobab fruit powder",
      reason: "traditional nutrient-dense fruit",
      cuisines: ["West African"],
      vegan: true,
      amount: 30.0,
      servingSize: "1 tbsp",
    },
    {
      name: "Okra",
      reason: "common stew vegetable",
      cuisines: ["West African"],
      vegan: true,
      amount: 20.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Bell peppers/tomatoes (in stews)",
      reason: "common stew base",
      cuisines: ["East African"],
      vegan: true,
      amount: 100.0,
      servingSize: "1 cup",
    },
    {
      name: "Papaya",
      reason: "common regional fruit",
      cuisines: ["East African"],
      vegan: true,
      amount: 88.0,
      servingSize: "1 cup",
    },
    {
      name: "Lemon (used generously)",
      reason: "common in stews and marinades",
      cuisines: ["East African"],
      vegan: true,
      amount: 30.0,
      servingSize: "1 whole",
    },
    {
      name: "Amla (Indian gooseberry)",
      reason: "traditional Ayurvedic superfood, exceptionally high vitamin C",
      cuisines: ["South Asian (Indian)"],
      vegan: true,
      amount: 600.0,
      servingSize: "1 fruit",
    },
    {
      name: "Lemon/lime (nimbu)",
      reason: "used generously across cuisine",
      cuisines: ["South Asian (Indian)"],
      vegan: true,
      amount: 30.0,
      servingSize: "1 whole",
    },
    {
      name: "Papaya (green papaya salad)",
      reason: "common dish base",
      cuisines: ["Southeast Asian"],
      vegan: true,
      amount: 88.0,
      servingSize: "1 cup",
    },
    {
      name: "Bok choy",
      reason: "common green",
      cuisines: ["East Asian"],
      vegan: true,
      amount: 45.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Napa cabbage (kimchi base)",
      reason: "fermented staple",
      cuisines: ["East Asian"],
      vegan: true,
      amount: 25.0,
      servingSize: "1 cup",
    },
    {
      name: "Citrus (yuzu, mandarin)",
      reason: "common regional fruit",
      cuisines: ["East Asian"],
      vegan: true,
      amount: 55.0,
      servingSize: "1 medium",
    },
    {
      name: "Parsley (tabbouleh)",
      reason: "traditional herb-forward salad",
      cuisines: ["Middle Eastern"],
      vegan: true,
      amount: 80.0,
      servingSize: "1 cup",
    },
    {
      name: "Pomegranate",
      reason: "common regional fruit",
      cuisines: ["Middle Eastern"],
      vegan: true,
      amount: 30.0,
      servingSize: "1 cup arils",
    },
    {
      name: "Oranges/citrus",
      reason: "common globally",
      vegan: true,
      amount: 60.0,
      servingSize: "1 medium",
    },
    {
      name: "Kiwi (for reference/variety)",
      reason: "widely known, good option when regional choices aren't available",
      vegan: true,
      amount: 70.0,
      servingSize: "1 fruit",
    },
    {
      name: "Red bell pepper",
      reason: "paired deliberately with lentils to lift non-heme iron absorption up to 6-fold",
      vegan: true,
      servingSize: "1 cup, in the lentil bowl recipe",
    },
    {
      name: "Kale",
      reason: "paired with lemon in the Day 2/3 soup recipes",
      vegan: true,
      servingSize: "1 cup, in the white bean soup recipe",
    },
    {
      name: "Cherry tomatoes",
      reason: "everyday pairing vegetable",
      vegan: true,
      servingSize: "handful, in the tofu scramble recipe",
    },
  ],
  vitamin_a: [
    {
      name: "Carrots",
      reason: "common everyday vegetable",
      cuisines: ["Canadian / North American"],
      vegan: true,
      amount: 1070.0,
      servingSize: "1 cup",
    },
    {
      name: "Sweet potato",
      reason: "common side dish",
      cuisines: ["Canadian / North American"],
      vegan: true,
      amount: 1400.0,
      servingSize: "1 medium",
    },
    {
      name: "Eggs",
      reason: "breakfast staple",
      cuisines: ["Canadian / North American"],
      vegan: false,
      amount: 160.0,
      servingSize: "2 whole",
    },
    {
      name: "Butter/dairy fat",
      reason: "traditional cooking fat",
      cuisines: ["Ukrainian / Eastern European"],
      vegan: false,
      amount: 95.0,
      servingSize: "1 tbsp",
    },
    {
      name: "Egg yolk",
      reason: "common in baking",
      cuisines: ["Ukrainian / Eastern European"],
      vegan: false,
      amount: 150.0,
      servingSize: "2 yolks",
    },
    {
      name: "Tomatoes (cooked, with oil)",
      reason: "sauce base; fat improves carotenoid absorption",
      cuisines: ["Italian"],
      vegan: true,
      amount: 40.0,
      servingSize: "1 cup",
    },
    {
      name: "Butternut squash (zucca)",
      reason: "traditional risotto ingredient",
      cuisines: ["Italian"],
      vegan: true,
      amount: 1140.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Sweet potato/squash",
      reason: "common side dish",
      cuisines: ["Spanish / Mediterranean"],
      vegan: true,
      amount: 1200.0,
      servingSize: "1 medium/cup",
    },
    {
      name: "Red peppers (pimientos)",
      reason: "common roasted vegetable",
      cuisines: ["Spanish / Mediterranean"],
      vegan: true,
      amount: 120.0,
      servingSize: "1 cup",
    },
    {
      name: "Mango",
      reason: "common regional fruit",
      cuisines: ["Mexican"],
      vegan: true,
      amount: 90.0,
      servingSize: "1 cup",
    },
    {
      name: "Sweet potato (camote)",
      reason: "common side dish",
      cuisines: ["Mexican"],
      vegan: true,
      amount: 1400.0,
      servingSize: "1 medium",
    },
    {
      name: "Sweet potato (boniato)",
      reason: "common staple side",
      cuisines: ["Cuban / Caribbean"],
      vegan: true,
      amount: 1400.0,
      servingSize: "1 medium",
    },
    {
      name: "Pumpkin/calabaza",
      reason: "common stew vegetable",
      cuisines: ["Cuban / Caribbean"],
      vegan: true,
      amount: 1000.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Red palm oil",
      reason: "traditional cooking fat, notably vitamin A-rich",
      cuisines: ["West African"],
      vegan: true,
      amount: 300.0,
      servingSize: "1 tbsp",
    },
    {
      name: "Carrots (in stews)",
      reason: "common stew vegetable",
      cuisines: ["East African"],
      vegan: true,
      amount: 1070.0,
      servingSize: "1 cup",
    },
    {
      name: "Mango/papaya",
      reason: "common regional fruit",
      cuisines: ["East African"],
      vegan: true,
      amount: 90.0,
      servingSize: "1 cup",
    },
    {
      name: "Pumpkin",
      reason: "common side dish",
      cuisines: ["East African"],
      vegan: true,
      amount: 1000.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Carrots (gajar)",
      reason: "gajar halwa, salads",
      cuisines: ["South Asian (Indian)"],
      vegan: true,
      amount: 1070.0,
      servingSize: "1 cup",
    },
    {
      name: "Mango (aam)",
      reason: "common regional fruit",
      cuisines: ["South Asian (Indian)"],
      vegan: true,
      amount: 90.0,
      servingSize: "1 cup",
    },
    {
      name: "Spinach (palak)",
      reason: "palak paneer, saag",
      cuisines: ["South Asian (Indian)"],
      vegan: true,
      amount: 570.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Squash (kabocha)",
      reason: "common in stews",
      cuisines: ["Southeast Asian"],
      vegan: true,
      amount: 1140.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Kabocha squash",
      reason: "common in Japanese/Korean cooking",
      cuisines: ["East Asian"],
      vegan: true,
      amount: 1140.0,
      servingSize: "1 cup cooked",
    },
    {
      name: "Apricots (dried)",
      reason: "common snack",
      cuisines: ["Middle Eastern"],
      vegan: true,
      amount: 60.0,
      servingSize: "1/4 cup",
    },
    {
      name: "Red peppers",
      reason: "common in stews and salads",
      cuisines: ["Middle Eastern"],
      vegan: true,
      amount: 120.0,
      servingSize: "1 cup",
    },
    {
      name: "Kale, cooked",
      reason: "also calcium and vitamin C in the same serving",
      vegan: true,
      servingSize: "1 cup",
    },
    {
      name: "Red bell pepper",
      reason: "double duty with vitamin C in the lentil bowl recipe",
      vegan: true,
      servingSize: "1 cup",
    },
  ],
};
